// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.0
// source: grpc/pb/yao.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       string                 `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Args          []byte                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`        // JSON-encoded argument array
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"` // seconds, 0 = server default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_grpc_pb_yao_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *RunRequest) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_grpc_pb_yao_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{1}
}

func (x *RunResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_grpc_pb_yao_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{2}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type ShellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timeout       int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"` // seconds, 0 = default 30s
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellRequest) Reset() {
	*x = ShellRequest{}
	mi := &file_grpc_pb_yao_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellRequest) ProtoMessage() {}

func (x *ShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellRequest.ProtoReflect.Descriptor instead.
func (*ShellRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{3}
}

func (x *ShellRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ShellRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ShellRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ShellRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type ShellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellResponse) Reset() {
	*x = ShellResponse{}
	mi := &file_grpc_pb_yao_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellResponse) ProtoMessage() {}

func (x *ShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellResponse.ProtoReflect.Descriptor instead.
func (*ShellResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{4}
}

func (x *ShellResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ShellResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ShellResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type APIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"` // HTTP method
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`     // openapi path
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIRequest) Reset() {
	*x = APIRequest{}
	mi := &file_grpc_pb_yao_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest) ProtoMessage() {}

func (x *APIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest.ProtoReflect.Descriptor instead.
func (*APIRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{5}
}

func (x *APIRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *APIRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *APIRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *APIRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type APIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // HTTP status code
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIResponse) Reset() {
	*x = APIResponse{}
	mi := &file_grpc_pb_yao_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse) ProtoMessage() {}

func (x *APIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse.ProtoReflect.Descriptor instead.
func (*APIResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{6}
}

func (x *APIResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *APIResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *APIResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type MCPListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPListRequest) Reset() {
	*x = MCPListRequest{}
	mi := &file_grpc_pb_yao_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPListRequest) ProtoMessage() {}

func (x *MCPListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPListRequest.ProtoReflect.Descriptor instead.
func (*MCPListRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{7}
}

func (x *MCPListRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type MCPListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []byte                 `protobuf:"bytes,1,opt,name=tools,proto3" json:"tools,omitempty"` // JSON array of tool definitions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPListResponse) Reset() {
	*x = MCPListResponse{}
	mi := &file_grpc_pb_yao_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPListResponse) ProtoMessage() {}

func (x *MCPListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPListResponse.ProtoReflect.Descriptor instead.
func (*MCPListResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{8}
}

func (x *MCPListResponse) GetTools() []byte {
	if x != nil {
		return x.Tools
	}
	return nil
}

type MCPCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Arguments     []byte                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"` // JSON-encoded arguments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPCallRequest) Reset() {
	*x = MCPCallRequest{}
	mi := &file_grpc_pb_yao_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPCallRequest) ProtoMessage() {}

func (x *MCPCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPCallRequest.ProtoReflect.Descriptor instead.
func (*MCPCallRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{9}
}

func (x *MCPCallRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MCPCallRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *MCPCallRequest) GetArguments() []byte {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type MCPCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // JSON-encoded result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPCallResponse) Reset() {
	*x = MCPCallResponse{}
	mi := &file_grpc_pb_yao_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPCallResponse) ProtoMessage() {}

func (x *MCPCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPCallResponse.ProtoReflect.Descriptor instead.
func (*MCPCallResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{10}
}

func (x *MCPCallResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type MCPResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []byte                 `protobuf:"bytes,1,opt,name=resources,proto3" json:"resources,omitempty"` // JSON array of resource definitions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPResourcesResponse) Reset() {
	*x = MCPResourcesResponse{}
	mi := &file_grpc_pb_yao_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPResourcesResponse) ProtoMessage() {}

func (x *MCPResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPResourcesResponse.ProtoReflect.Descriptor instead.
func (*MCPResourcesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{11}
}

func (x *MCPResourcesResponse) GetResources() []byte {
	if x != nil {
		return x.Resources
	}
	return nil
}

type MCPResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPResourceRequest) Reset() {
	*x = MCPResourceRequest{}
	mi := &file_grpc_pb_yao_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPResourceRequest) ProtoMessage() {}

func (x *MCPResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPResourceRequest.ProtoReflect.Descriptor instead.
func (*MCPResourceRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{12}
}

func (x *MCPResourceRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MCPResourceRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type MCPResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []byte                 `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"` // JSON-encoded resource contents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPResourceResponse) Reset() {
	*x = MCPResourceResponse{}
	mi := &file_grpc_pb_yao_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPResourceResponse) ProtoMessage() {}

func (x *MCPResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPResourceResponse.ProtoReflect.Descriptor instead.
func (*MCPResourceResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{13}
}

func (x *MCPResourceResponse) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     string                 `protobuf:"bytes,1,opt,name=connector,proto3" json:"connector,omitempty"` // connector ID
	Messages      []byte                 `protobuf:"bytes,2,opt,name=messages,proto3" json:"messages,omitempty"`   // JSON-encoded message array
	Options       []byte                 `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`     // JSON-encoded options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_grpc_pb_yao_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{14}
}

func (x *ChatRequest) GetConnector() string {
	if x != nil {
		return x.Connector
	}
	return ""
}

func (x *ChatRequest) GetMessages() []byte {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded completion result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_grpc_pb_yao_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{15}
}

func (x *ChatResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChatChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded chunk
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_grpc_pb_yao_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{16}
}

func (x *ChatChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChatChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type AgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   string                 `protobuf:"bytes,1,opt,name=assistant_id,json=assistantId,proto3" json:"assistant_id,omitempty"`
	Messages      []byte                 `protobuf:"bytes,2,opt,name=messages,proto3" json:"messages,omitempty"` // JSON-encoded message array
	Options       []byte                 `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`   // JSON-encoded options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_grpc_pb_yao_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{17}
}

func (x *AgentRequest) GetAssistantId() string {
	if x != nil {
		return x.AssistantId
	}
	return ""
}

func (x *AgentRequest) GetMessages() []byte {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *AgentRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

// Each chunk carries JSON-serialized agent/output/message.Message.
type AgentChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentChunk) Reset() {
	*x = AgentChunk{}
	mi := &file_grpc_pb_yao_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentChunk) ProtoMessage() {}

func (x *AgentChunk) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentChunk.ProtoReflect.Descriptor instead.
func (*AgentChunk) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{18}
}

func (x *AgentChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AgentChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpc_pb_yao_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{19}
}

type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_grpc_pb_yao_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{20}
}

func (x *HealthzResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	CpuPercent    int32                  `protobuf:"varint,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemBytes      int64                  `protobuf:"varint,3,opt,name=mem_bytes,json=memBytes,proto3" json:"mem_bytes,omitempty"`
	RunningProcs  int32                  `protobuf:"varint,4,opt,name=running_procs,json=runningProcs,proto3" json:"running_procs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_grpc_pb_yao_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuPercent() int32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HeartbeatRequest) GetMemBytes() int64 {
	if x != nil {
		return x.MemBytes
	}
	return 0
}

func (x *HeartbeatRequest) GetRunningProcs() int32 {
	if x != nil {
		return x.RunningProcs
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "ok" or "shutdown"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_grpc_pb_yao_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_pb_yao_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_grpc_pb_yao_proto_rawDescGZIP(), []int{22}
}

func (x *HeartbeatResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_grpc_pb_yao_proto protoreflect.FileDescriptor

const file_grpc_pb_yao_proto_rawDesc = "" +
	"\n" +
	"\x11grpc/pb/yao.proto\x12\x03yao\"T\n" +
	"\n" +
	"RunRequest\x12\x18\n" +
	"\aprocess\x18\x01 \x01(\tR\aprocess\x12\x12\n" +
	"\x04args\x18\x02 \x01(\fR\x04args\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\"!\n" +
	"\vRunResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"/\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\"\xbc\x01\n" +
	"\fShellRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12,\n" +
	"\x03env\x18\x03 \x03(\v2\x1a.yao.ShellRequest.EnvEntryR\x03env\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\rShellResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\fR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"\xc0\x01\n" +
	"\n" +
	"APIRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x126\n" +
	"\aheaders\x18\x03 \x03(\v2\x1c.yao.APIRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x01\n" +
	"\vAPIResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x127\n" +
	"\aheaders\x18\x02 \x03(\v2\x1d.yao.APIResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x0eMCPListRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"'\n" +
	"\x0fMCPListResponse\x12\x14\n" +
	"\x05tools\x18\x01 \x01(\fR\x05tools\"a\n" +
	"\x0eMCPCallRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\fR\targuments\")\n" +
	"\x0fMCPCallResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"4\n" +
	"\x14MCPResourcesResponse\x12\x1c\n" +
	"\tresources\x18\x01 \x01(\fR\tresources\"E\n" +
	"\x12MCPResourceRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\"1\n" +
	"\x13MCPResourceResponse\x12\x1a\n" +
	"\bcontents\x18\x01 \x01(\fR\bcontents\"a\n" +
	"\vChatRequest\x12\x1c\n" +
	"\tconnector\x18\x01 \x01(\tR\tconnector\x12\x1a\n" +
	"\bmessages\x18\x02 \x01(\fR\bmessages\x12\x18\n" +
	"\aoptions\x18\x03 \x01(\fR\aoptions\"\"\n" +
	"\fChatResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"3\n" +
	"\tChatChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\"g\n" +
	"\fAgentRequest\x12!\n" +
	"\fassistant_id\x18\x01 \x01(\tR\vassistantId\x12\x1a\n" +
	"\bmessages\x18\x02 \x01(\fR\bmessages\x12\x18\n" +
	"\aoptions\x18\x03 \x01(\fR\aoptions\"4\n" +
	"\n" +
	"AgentChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\"\a\n" +
	"\x05Empty\")\n" +
	"\x0fHealthzResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x94\x01\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x05R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmem_bytes\x18\x03 \x01(\x03R\bmemBytes\x12#\n" +
	"\rrunning_procs\x18\x04 \x01(\x05R\frunningProcs\"+\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action2\xf4\x05\n" +
	"\x03Yao\x12(\n" +
	"\x03Run\x12\x0f.yao.RunRequest\x1a\x10.yao.RunResponse\x12'\n" +
	"\x06Stream\x12\x0f.yao.RunRequest\x1a\n" +
	".yao.Chunk0\x01\x12.\n" +
	"\x05Shell\x12\x11.yao.ShellRequest\x1a\x12.yao.ShellResponse\x12.\n" +
	"\vShellStream\x12\x11.yao.ShellRequest\x1a\n" +
	".yao.Chunk0\x01\x12(\n" +
	"\x03API\x12\x0f.yao.APIRequest\x1a\x10.yao.APIResponse\x129\n" +
	"\fMCPListTools\x12\x13.yao.MCPListRequest\x1a\x14.yao.MCPListResponse\x128\n" +
	"\vMCPCallTool\x12\x13.yao.MCPCallRequest\x1a\x14.yao.MCPCallResponse\x12B\n" +
	"\x10MCPListResources\x12\x13.yao.MCPListRequest\x1a\x19.yao.MCPResourcesResponse\x12D\n" +
	"\x0fMCPReadResource\x12\x17.yao.MCPResourceRequest\x1a\x18.yao.MCPResourceResponse\x126\n" +
	"\x0fChatCompletions\x12\x10.yao.ChatRequest\x1a\x11.yao.ChatResponse\x12;\n" +
	"\x15ChatCompletionsStream\x12\x10.yao.ChatRequest\x1a\x0e.yao.ChatChunk0\x01\x123\n" +
	"\vAgentStream\x12\x11.yao.AgentRequest\x1a\x0f.yao.AgentChunk0\x01\x12+\n" +
	"\aHealthz\x12\n" +
	".yao.Empty\x1a\x14.yao.HealthzResponse\x12:\n" +
	"\tHeartbeat\x12\x15.yao.HeartbeatRequest\x1a\x16.yao.HeartbeatResponseB\x1fZ\x1dgithub.com/yaoapp/yao/grpc/pbb\x06proto3"

var (
	file_grpc_pb_yao_proto_rawDescOnce sync.Once
	file_grpc_pb_yao_proto_rawDescData []byte
)

func file_grpc_pb_yao_proto_rawDescGZIP() []byte {
	file_grpc_pb_yao_proto_rawDescOnce.Do(func() {
		file_grpc_pb_yao_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_pb_yao_proto_rawDesc), len(file_grpc_pb_yao_proto_rawDesc)))
	})
	return file_grpc_pb_yao_proto_rawDescData
}

var file_grpc_pb_yao_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_grpc_pb_yao_proto_goTypes = []any{
	(*RunRequest)(nil),           // 0: yao.RunRequest
	(*RunResponse)(nil),          // 1: yao.RunResponse
	(*Chunk)(nil),                // 2: yao.Chunk
	(*ShellRequest)(nil),         // 3: yao.ShellRequest
	(*ShellResponse)(nil),        // 4: yao.ShellResponse
	(*APIRequest)(nil),           // 5: yao.APIRequest
	(*APIResponse)(nil),          // 6: yao.APIResponse
	(*MCPListRequest)(nil),       // 7: yao.MCPListRequest
	(*MCPListResponse)(nil),      // 8: yao.MCPListResponse
	(*MCPCallRequest)(nil),       // 9: yao.MCPCallRequest
	(*MCPCallResponse)(nil),      // 10: yao.MCPCallResponse
	(*MCPResourcesResponse)(nil), // 11: yao.MCPResourcesResponse
	(*MCPResourceRequest)(nil),   // 12: yao.MCPResourceRequest
	(*MCPResourceResponse)(nil),  // 13: yao.MCPResourceResponse
	(*ChatRequest)(nil),          // 14: yao.ChatRequest
	(*ChatResponse)(nil),         // 15: yao.ChatResponse
	(*ChatChunk)(nil),            // 16: yao.ChatChunk
	(*AgentRequest)(nil),         // 17: yao.AgentRequest
	(*AgentChunk)(nil),           // 18: yao.AgentChunk
	(*Empty)(nil),                // 19: yao.Empty
	(*HealthzResponse)(nil),      // 20: yao.HealthzResponse
	(*HeartbeatRequest)(nil),     // 21: yao.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 22: yao.HeartbeatResponse
	nil,                          // 23: yao.ShellRequest.EnvEntry
	nil,                          // 24: yao.APIRequest.HeadersEntry
	nil,                          // 25: yao.APIResponse.HeadersEntry
}
var file_grpc_pb_yao_proto_depIdxs = []int32{
	23, // 0: yao.ShellRequest.env:type_name -> yao.ShellRequest.EnvEntry
	24, // 1: yao.APIRequest.headers:type_name -> yao.APIRequest.HeadersEntry
	25, // 2: yao.APIResponse.headers:type_name -> yao.APIResponse.HeadersEntry
	0,  // 3: yao.Yao.Run:input_type -> yao.RunRequest
	0,  // 4: yao.Yao.Stream:input_type -> yao.RunRequest
	3,  // 5: yao.Yao.Shell:input_type -> yao.ShellRequest
	3,  // 6: yao.Yao.ShellStream:input_type -> yao.ShellRequest
	5,  // 7: yao.Yao.API:input_type -> yao.APIRequest
	7,  // 8: yao.Yao.MCPListTools:input_type -> yao.MCPListRequest
	9,  // 9: yao.Yao.MCPCallTool:input_type -> yao.MCPCallRequest
	7,  // 10: yao.Yao.MCPListResources:input_type -> yao.MCPListRequest
	12, // 11: yao.Yao.MCPReadResource:input_type -> yao.MCPResourceRequest
	14, // 12: yao.Yao.ChatCompletions:input_type -> yao.ChatRequest
	14, // 13: yao.Yao.ChatCompletionsStream:input_type -> yao.ChatRequest
	17, // 14: yao.Yao.AgentStream:input_type -> yao.AgentRequest
	19, // 15: yao.Yao.Healthz:input_type -> yao.Empty
	21, // 16: yao.Yao.Heartbeat:input_type -> yao.HeartbeatRequest
	1,  // 17: yao.Yao.Run:output_type -> yao.RunResponse
	2,  // 18: yao.Yao.Stream:output_type -> yao.Chunk
	4,  // 19: yao.Yao.Shell:output_type -> yao.ShellResponse
	2,  // 20: yao.Yao.ShellStream:output_type -> yao.Chunk
	6,  // 21: yao.Yao.API:output_type -> yao.APIResponse
	8,  // 22: yao.Yao.MCPListTools:output_type -> yao.MCPListResponse
	10, // 23: yao.Yao.MCPCallTool:output_type -> yao.MCPCallResponse
	11, // 24: yao.Yao.MCPListResources:output_type -> yao.MCPResourcesResponse
	13, // 25: yao.Yao.MCPReadResource:output_type -> yao.MCPResourceResponse
	15, // 26: yao.Yao.ChatCompletions:output_type -> yao.ChatResponse
	16, // 27: yao.Yao.ChatCompletionsStream:output_type -> yao.ChatChunk
	18, // 28: yao.Yao.AgentStream:output_type -> yao.AgentChunk
	20, // 29: yao.Yao.Healthz:output_type -> yao.HealthzResponse
	22, // 30: yao.Yao.Heartbeat:output_type -> yao.HeartbeatResponse
	17, // [17:31] is the sub-list for method output_type
	3,  // [3:17] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_pb_yao_proto_init() }
func file_grpc_pb_yao_proto_init() {
	if File_grpc_pb_yao_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_pb_yao_proto_rawDesc), len(file_grpc_pb_yao_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_pb_yao_proto_goTypes,
		DependencyIndexes: file_grpc_pb_yao_proto_depIdxs,
		MessageInfos:      file_grpc_pb_yao_proto_msgTypes,
	}.Build()
	File_grpc_pb_yao_proto = out.File
	file_grpc_pb_yao_proto_goTypes = nil
	file_grpc_pb_yao_proto_depIdxs = nil
}
