// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.0
// source: systemquery.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPortsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPortsRequest) Reset() {
	*x = ListPortsRequest{}
	mi := &file_systemquery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPortsRequest) ProtoMessage() {}

func (x *ListPortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_systemquery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPortsRequest.ProtoReflect.Descriptor instead.
func (*ListPortsRequest) Descriptor() ([]byte, []int) {
	return file_systemquery_proto_rawDescGZIP(), []int{0}
}

type ListPortsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []*PortInfo            `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPortsResponse) Reset() {
	*x = ListPortsResponse{}
	mi := &file_systemquery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPortsResponse) ProtoMessage() {}

func (x *ListPortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_systemquery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPortsResponse.ProtoReflect.Descriptor instead.
func (*ListPortsResponse) Descriptor() ([]byte, []int) {
	return file_systemquery_proto_rawDescGZIP(), []int{1}
}

func (x *ListPortsResponse) GetPorts() []*PortInfo {
	if x != nil {
		return x.Ports
	}
	return nil
}

type ListProcessesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkipCpuSample bool                   `protobuf:"varint,1,opt,name=skip_cpu_sample,json=skipCpuSample,proto3" json:"skip_cpu_sample,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesRequest) Reset() {
	*x = ListProcessesRequest{}
	mi := &file_systemquery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesRequest) ProtoMessage() {}

func (x *ListProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_systemquery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesRequest.ProtoReflect.Descriptor instead.
func (*ListProcessesRequest) Descriptor() ([]byte, []int) {
	return file_systemquery_proto_rawDescGZIP(), []int{2}
}

func (x *ListProcessesRequest) GetSkipCpuSample() bool {
	if x != nil {
		return x.SkipCpuSample
	}
	return false
}

type ListProcessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	Load          *SystemLoad            `protobuf:"bytes,2,opt,name=load,proto3" json:"load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesResponse) Reset() {
	*x = ListProcessesResponse{}
	mi := &file_systemquery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesResponse) ProtoMessage() {}

func (x *ListProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_systemquery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesResponse.ProtoReflect.Descriptor instead.
func (*ListProcessesResponse) Descriptor() ([]byte, []int) {
	return file_systemquery_proto_rawDescGZIP(), []int{3}
}

func (x *ListProcessesResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *ListProcessesResponse) GetLoad() *SystemLoad {
	if x != nil {
		return x.Load
	}
	return nil
}

type PortInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Process       string                 `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`
	Pid           int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Command       string                 `protobuf:"bytes,7,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortInfo) Reset() {
	*x = PortInfo{}
	mi := &file_systemquery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortInfo) ProtoMessage() {}

func (x *PortInfo) ProtoReflect() protoreflect.Message {
	mi := &file_systemquery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortInfo.ProtoReflect.Descriptor instead.
func (*PortInfo) Descriptor() ([]byte, []int) {
	return file_systemquery_proto_rawDescGZIP(), []int{4}
}

func (x *PortInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PortInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PortInfo) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *PortInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PortInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PortInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PortInfo) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          int32                  `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	CpuPercent    float32                `protobuf:"fixed32,6,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float32                `protobuf:"fixed32,7,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	RssBytes      int64                  `protobuf:"varint,8,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	VszBytes      int64                  `protobuf:"varint,9,opt,name=vsz_bytes,json=vszBytes,proto3" json:"vsz_bytes,omitempty"`
	StartTime     int64                  `protobuf:"varint,10,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	CpuTimeMs     int64                  `protobuf:"varint,11,opt,name=cpu_time_ms,json=cpuTimeMs,proto3" json:"cpu_time_ms,omitempty"`
	Threads       int32                  `protobuf:"varint,12,opt,name=threads,proto3" json:"threads,omitempty"`
	OpenFiles     int32                  `protobuf:"varint,13,opt,name=open_files,json=openFiles,proto3" json:"open_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_systemquery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_systemquery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_systemquery_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessInfo) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ProcessInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProcessInfo) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemPercent() float32 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *ProcessInfo) GetRssBytes() int64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *ProcessInfo) GetVszBytes() int64 {
	if x != nil {
		return x.VszBytes
	}
	return 0
}

func (x *ProcessInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ProcessInfo) GetCpuTimeMs() int64 {
	if x != nil {
		return x.CpuTimeMs
	}
	return 0
}

func (x *ProcessInfo) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *ProcessInfo) GetOpenFiles() int32 {
	if x != nil {
		return x.OpenFiles
	}
	return 0
}

type SystemLoad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Load1         float32                `protobuf:"fixed32,1,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5         float32                `protobuf:"fixed32,2,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15        float32                `protobuf:"fixed32,3,opt,name=load15,proto3" json:"load15,omitempty"`
	MemTotal      int64                  `protobuf:"varint,4,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsed       int64                  `protobuf:"varint,5,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	MemAvailable  int64                  `protobuf:"varint,6,opt,name=mem_available,json=memAvailable,proto3" json:"mem_available,omitempty"`
	SwapTotal     int64                  `protobuf:"varint,7,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapUsed      int64                  `protobuf:"varint,8,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	CpuCount      int32                  `protobuf:"varint,9,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,10,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	UptimeSec     int64                  `protobuf:"varint,11,opt,name=uptime_sec,json=uptimeSec,proto3" json:"uptime_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemLoad) Reset() {
	*x = SystemLoad{}
	mi := &file_systemquery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemLoad) ProtoMessage() {}

func (x *SystemLoad) ProtoReflect() protoreflect.Message {
	mi := &file_systemquery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemLoad.ProtoReflect.Descriptor instead.
func (*SystemLoad) Descriptor() ([]byte, []int) {
	return file_systemquery_proto_rawDescGZIP(), []int{6}
}

func (x *SystemLoad) GetLoad1() float32 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *SystemLoad) GetLoad5() float32 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *SystemLoad) GetLoad15() float32 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *SystemLoad) GetMemTotal() int64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *SystemLoad) GetMemUsed() int64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *SystemLoad) GetMemAvailable() int64 {
	if x != nil {
		return x.MemAvailable
	}
	return 0
}

func (x *SystemLoad) GetSwapTotal() int64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *SystemLoad) GetSwapUsed() int64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

func (x *SystemLoad) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *SystemLoad) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemLoad) GetUptimeSec() int64 {
	if x != nil {
		return x.UptimeSec
	}
	return 0
}

var File_systemquery_proto protoreflect.FileDescriptor

const file_systemquery_proto_rawDesc = "" +
	"\n" +
	"\x11systemquery.proto\x12\vsystemquery\"\x12\n" +
	"\x10ListPortsRequest\"@\n" +
	"\x11ListPortsResponse\x12+\n" +
	"\x05ports\x18\x01 \x03(\v2\x15.systemquery.PortInfoR\x05ports\">\n" +
	"\x14ListProcessesRequest\x12&\n" +
	"\x0fskip_cpu_sample\x18\x01 \x01(\bR\rskipCpuSample\"|\n" +
	"\x15ListProcessesResponse\x126\n" +
	"\tprocesses\x18\x01 \x03(\v2\x18.systemquery.ProcessInfoR\tprocesses\x12+\n" +
	"\x04load\x18\x02 \x01(\v2\x17.systemquery.SystemLoadR\x04load\"\xb0\x01\n" +
	"\bPortInfo\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x18\n" +
	"\aprocess\x18\x03 \x01(\tR\aprocess\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x18\n" +
	"\acommand\x18\a \x01(\tR\acommand\"\xeb\x02\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x05R\x04ppid\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1f\n" +
	"\vcpu_percent\x18\x06 \x01(\x02R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\a \x01(\x02R\n" +
	"memPercent\x12\x1b\n" +
	"\trss_bytes\x18\b \x01(\x03R\brssBytes\x12\x1b\n" +
	"\tvsz_bytes\x18\t \x01(\x03R\bvszBytes\x12\x1d\n" +
	"\n" +
	"start_time\x18\n" +
	" \x01(\x03R\tstartTime\x12\x1e\n" +
	"\vcpu_time_ms\x18\v \x01(\x03R\tcpuTimeMs\x12\x18\n" +
	"\athreads\x18\f \x01(\x05R\athreads\x12\x1d\n" +
	"\n" +
	"open_files\x18\r \x01(\x05R\topenFiles\"\xc2\x02\n" +
	"\n" +
	"SystemLoad\x12\x14\n" +
	"\x05load1\x18\x01 \x01(\x02R\x05load1\x12\x14\n" +
	"\x05load5\x18\x02 \x01(\x02R\x05load5\x12\x16\n" +
	"\x06load15\x18\x03 \x01(\x02R\x06load15\x12\x1b\n" +
	"\tmem_total\x18\x04 \x01(\x03R\bmemTotal\x12\x19\n" +
	"\bmem_used\x18\x05 \x01(\x03R\amemUsed\x12#\n" +
	"\rmem_available\x18\x06 \x01(\x03R\fmemAvailable\x12\x1d\n" +
	"\n" +
	"swap_total\x18\a \x01(\x03R\tswapTotal\x12\x1b\n" +
	"\tswap_used\x18\b \x01(\x03R\bswapUsed\x12\x1b\n" +
	"\tcpu_count\x18\t \x01(\x05R\bcpuCount\x12\x1b\n" +
	"\tcpu_usage\x18\n" +
	" \x01(\x02R\bcpuUsage\x12\x1d\n" +
	"\n" +
	"uptime_sec\x18\v \x01(\x03R\tuptimeSec2\xb1\x01\n" +
	"\vSystemQuery\x12J\n" +
	"\tListPorts\x12\x1d.systemquery.ListPortsRequest\x1a\x1e.systemquery.ListPortsResponse\x12V\n" +
	"\rListProcesses\x12!.systemquery.ListProcessesRequest\x1a\".systemquery.ListProcessesResponseB*Z(github.com/yaoapp/yao/tai/systemquery/pbb\x06proto3"

var (
	file_systemquery_proto_rawDescOnce sync.Once
	file_systemquery_proto_rawDescData []byte
)

func file_systemquery_proto_rawDescGZIP() []byte {
	file_systemquery_proto_rawDescOnce.Do(func() {
		file_systemquery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_systemquery_proto_rawDesc), len(file_systemquery_proto_rawDesc)))
	})
	return file_systemquery_proto_rawDescData
}

var file_systemquery_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_systemquery_proto_goTypes = []any{
	(*ListPortsRequest)(nil),      // 0: systemquery.ListPortsRequest
	(*ListPortsResponse)(nil),     // 1: systemquery.ListPortsResponse
	(*ListProcessesRequest)(nil),  // 2: systemquery.ListProcessesRequest
	(*ListProcessesResponse)(nil), // 3: systemquery.ListProcessesResponse
	(*PortInfo)(nil),              // 4: systemquery.PortInfo
	(*ProcessInfo)(nil),           // 5: systemquery.ProcessInfo
	(*SystemLoad)(nil),            // 6: systemquery.SystemLoad
}
var file_systemquery_proto_depIdxs = []int32{
	4, // 0: systemquery.ListPortsResponse.ports:type_name -> systemquery.PortInfo
	5, // 1: systemquery.ListProcessesResponse.processes:type_name -> systemquery.ProcessInfo
	6, // 2: systemquery.ListProcessesResponse.load:type_name -> systemquery.SystemLoad
	0, // 3: systemquery.SystemQuery.ListPorts:input_type -> systemquery.ListPortsRequest
	2, // 4: systemquery.SystemQuery.ListProcesses:input_type -> systemquery.ListProcessesRequest
	1, // 5: systemquery.SystemQuery.ListPorts:output_type -> systemquery.ListPortsResponse
	3, // 6: systemquery.SystemQuery.ListProcesses:output_type -> systemquery.ListProcessesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_systemquery_proto_init() }
func file_systemquery_proto_init() {
	if File_systemquery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_systemquery_proto_rawDesc), len(file_systemquery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_systemquery_proto_goTypes,
		DependencyIndexes: file_systemquery_proto_depIdxs,
		MessageInfos:      file_systemquery_proto_msgTypes,
	}.Build()
	File_systemquery_proto = out.File
	file_systemquery_proto_goTypes = nil
	file_systemquery_proto_depIdxs = nil
}
