// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.0
// source: systemquery.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemQuery_ListPorts_FullMethodName     = "/systemquery.SystemQuery/ListPorts"
	SystemQuery_ListProcesses_FullMethodName = "/systemquery.SystemQuery/ListProcesses"
)

// SystemQueryClient is the client API for SystemQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemQueryClient interface {
	ListPorts(ctx context.Context, in *ListPortsRequest, opts ...grpc.CallOption) (*ListPortsResponse, error)
	ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error)
}

type systemQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemQueryClient(cc grpc.ClientConnInterface) SystemQueryClient {
	return &systemQueryClient{cc}
}

func (c *systemQueryClient) ListPorts(ctx context.Context, in *ListPortsRequest, opts ...grpc.CallOption) (*ListPortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPortsResponse)
	err := c.cc.Invoke(ctx, SystemQuery_ListPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemQueryClient) ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProcessesResponse)
	err := c.cc.Invoke(ctx, SystemQuery_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemQueryServer is the server API for SystemQuery service.
// All implementations must embed UnimplementedSystemQueryServer
// for forward compatibility.
type SystemQueryServer interface {
	ListPorts(context.Context, *ListPortsRequest) (*ListPortsResponse, error)
	ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error)
	mustEmbedUnimplementedSystemQueryServer()
}

// UnimplementedSystemQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemQueryServer struct{}

func (UnimplementedSystemQueryServer) ListPorts(context.Context, *ListPortsRequest) (*ListPortsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPorts not implemented")
}
func (UnimplementedSystemQueryServer) ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedSystemQueryServer) mustEmbedUnimplementedSystemQueryServer() {}
func (UnimplementedSystemQueryServer) testEmbeddedByValue()                     {}

// UnsafeSystemQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemQueryServer will
// result in compilation errors.
type UnsafeSystemQueryServer interface {
	mustEmbedUnimplementedSystemQueryServer()
}

func RegisterSystemQueryServer(s grpc.ServiceRegistrar, srv SystemQueryServer) {
	// If the following call panics, it indicates UnimplementedSystemQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemQuery_ServiceDesc, srv)
}

func _SystemQuery_ListPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemQueryServer).ListPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemQuery_ListPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemQueryServer).ListPorts(ctx, req.(*ListPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemQuery_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemQueryServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemQuery_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemQueryServer).ListProcesses(ctx, req.(*ListProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemQuery_ServiceDesc is the grpc.ServiceDesc for SystemQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "systemquery.SystemQuery",
	HandlerType: (*SystemQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPorts",
			Handler:    _SystemQuery_ListPorts_Handler,
		},
		{
			MethodName: "ListProcesses",
			Handler:    _SystemQuery_ListProcesses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "systemquery.proto",
}
