package types

// Phase - execution phase
type Phase string

const (
	PhaseInspiration Phase = "inspiration" // P0: Clock only
	PhaseGoals       Phase = "goals"       // P1
	PhaseTasks       Phase = "tasks"       // P2
	PhaseRun         Phase = "run"         // P3
	PhaseDelivery    Phase = "delivery"    // P4
	PhaseLearning    Phase = "learning"    // P5
)

// AllPhases for iteration
var AllPhases = []Phase{
	PhaseInspiration, PhaseGoals, PhaseTasks,
	PhaseRun, PhaseDelivery, PhaseLearning,
}

// ClockMode - clock trigger mode
type ClockMode string

const (
	ClockTimes    ClockMode = "times"    // run at specific times
	ClockInterval ClockMode = "interval" // run every X duration
	ClockDaemon   ClockMode = "daemon"   // run continuously
)

// TriggerType - trigger source
type TriggerType string

const (
	TriggerClock TriggerType = "clock"
	TriggerHuman TriggerType = "human"
	TriggerEvent TriggerType = "event"
)

// ExecStatus - execution status
type ExecStatus string

const (
	ExecPending   ExecStatus = "pending"
	ExecRunning   ExecStatus = "running"
	ExecCompleted ExecStatus = "completed"
	ExecFailed    ExecStatus = "failed"
	ExecCancelled ExecStatus = "cancelled"
)

// RobotStatus - matches __yao.member.robot_status
type RobotStatus string

const (
	RobotIdle        RobotStatus = "idle"
	RobotWorking     RobotStatus = "working"
	RobotPaused      RobotStatus = "paused"
	RobotError       RobotStatus = "error"
	RobotMaintenance RobotStatus = "maintenance"
)

// InterventionAction - human intervention action
// Format: category.action (e.g., "task.add", "goal.adjust")
type InterventionAction string

const (
	// Task operations
	ActionTaskAdd    InterventionAction = "task.add"    // add a new task
	ActionTaskCancel InterventionAction = "task.cancel" // cancel a task
	ActionTaskUpdate InterventionAction = "task.update" // update task details

	// Goal operations
	ActionGoalAdjust   InterventionAction = "goal.adjust"   // modify current goal
	ActionGoalAdd      InterventionAction = "goal.add"      // add a new goal
	ActionGoalComplete InterventionAction = "goal.complete" // mark goal as complete
	ActionGoalCancel   InterventionAction = "goal.cancel"   // cancel a goal

	// Plan operations (schedule for later)
	ActionPlanAdd    InterventionAction = "plan.add"    // add to plan queue
	ActionPlanRemove InterventionAction = "plan.remove" // remove from plan queue
	ActionPlanUpdate InterventionAction = "plan.update" // update planned item

	// Instruction (direct command)
	ActionInstruct InterventionAction = "instruct" // direct instruction to robot
)

// Priority - task/goal priority
type Priority string

const (
	PriorityHigh   Priority = "high"
	PriorityNormal Priority = "normal"
	PriorityLow    Priority = "low"
)

// DeliveryType - output delivery type
type DeliveryType string

const (
	DeliveryEmail   DeliveryType = "email"
	DeliveryFile    DeliveryType = "file"
	DeliveryWebhook DeliveryType = "webhook"
	DeliveryNotify  DeliveryType = "notify"
)

// DedupResult - deduplication result
type DedupResult string

const (
	DedupSkip    DedupResult = "skip"    // skip execution
	DedupMerge   DedupResult = "merge"   // merge with existing
	DedupProceed DedupResult = "proceed" // proceed normally
)

// EventSource - event trigger source
type EventSource string

const (
	EventWebhook  EventSource = "webhook"  // HTTP webhook
	EventDatabase EventSource = "database" // DB change trigger
)

// LearningType - learning entry type
type LearningType string

const (
	LearnExecution LearningType = "execution" // execution record
	LearnFeedback  LearningType = "feedback"  // error/fix feedback
	LearnInsight   LearningType = "insight"   // pattern/tip insight
)

// TaskSource - how task was created
type TaskSource string

const (
	TaskSourceAuto  TaskSource = "auto"  // generated by P2 (task planning)
	TaskSourceHuman TaskSource = "human" // added via human intervention
	TaskSourceEvent TaskSource = "event" // added via event trigger
)

// ExecutorType - task executor type
type ExecutorType string

const (
	ExecutorAssistant ExecutorType = "assistant"
	ExecutorMCP       ExecutorType = "mcp"
	ExecutorProcess   ExecutorType = "process"
)

// TaskStatus - task execution status
type TaskStatus string

const (
	TaskPending   TaskStatus = "pending"
	TaskRunning   TaskStatus = "running"
	TaskCompleted TaskStatus = "completed"
	TaskFailed    TaskStatus = "failed"
	TaskSkipped   TaskStatus = "skipped"
	TaskCancelled TaskStatus = "cancelled"
)

// InsertPosition - where to insert task in queue
type InsertPosition string

const (
	InsertFirst InsertPosition = "first" // insert at beginning (highest priority)
	InsertLast  InsertPosition = "last"  // append at end (default)
	InsertNext  InsertPosition = "next"  // insert after current task
	InsertAt    InsertPosition = "at"    // insert at specific index (use AtIndex)
)
