package dsh

import (
	"bytes"
	"text/template"
)

// ConnectorConfig holds LLM connector settings for cordis.yml rendering.
type ConnectorConfig struct {
	BaseURL         string
	Thinking        string
	ReasoningEffort string
	MaxTokens       int
	IsWindows       bool
}

const cordisTemplate = `# Generated by Yao DSH Runner
- id: yaoapp-jsonrpc-stream
  name: '@yaoapp/dsh-sdk-jsonrpc-stream'
  config:
    maxTokensAsSuccess: true

- id: llm-deepseek
  name: '@deepseek-ai/dsh-llm-deepseek'
  config:
{{- if .BaseURL }}
    baseURL: {{ .BaseURL }}
{{- end }}
    apiKeyEnv: DEEPSEEK_API_KEY
    thinking: {{ or .Thinking "enabled" }}
    reasoningEffort: {{ if eq .Thinking "disabled" }}off{{ else }}{{ or .ReasoningEffort "high" }}{{ end }}
{{- if gt .MaxTokens 0 }}
    maxTokens: {{ .MaxTokens }}
{{- end }}

- id: subprocess
  name: '@deepseek-ai/dsh-subprocess-local'

{{- if .IsWindows }}

- id: pwsh
  name: '@deepseek-ai/dsh-pwsh-local'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()
    timeoutMs: 120000

- id: agent-spine
  name: '@deepseek-ai/dsh-agent-spine-demo'
  config:
    persona: !!js process.env.DSH_SYSTEM_PROMPT ?? 'You are a coding agent.'
    workspaceContext:
      maxBytes: 16384
    toolBash: false
    toolJobs: false

- id: shell-env
  name: '@deepseek-ai/dsh-shell-env'

- id: tool-pwsh
  name: '@deepseek-ai/dsh-tool-pwsh'

{{- else }}

- id: bash
  name: '@deepseek-ai/dsh-bash-local'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()
    timeoutMs: 120000

- id: agent-spine
  name: '@deepseek-ai/dsh-agent-spine-demo'
  config:
    persona: !!js process.env.DSH_SYSTEM_PROMPT ?? 'You are a coding agent.'
    workspaceContext:
      maxBytes: 16384
    toolBash:
      enableRunInBackground: false
    toolJobs: false

{{- end }}

- id: subagent
  name: '@deepseek-ai/dsh-subagent'

- id: subagent-spawn-in-process
  name: '@deepseek-ai/dsh-subagent-spawn-in-process'
  config:
    providerName: spawn

- id: tool-subagent
  name: '@deepseek-ai/dsh-tool-subagent'
  config:
    provider: spawn
    toolName: subagent
    enableRunInBackground: false

- id: tool-todo
  name: '@deepseek-ai/dsh-tool-todo'
  config:
    allowParallelInProgress: true

- id: fs-local
  name: '@deepseek-ai/dsh-fs-local'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()

- id: fs-observation-policy
  name: '@deepseek-ai/dsh-fs-observation-policy'

- id: tool-fs
  name: '@deepseek-ai/dsh-tool-fs'

- id: token-meter
  name: '@deepseek-ai/dsh-token-meter'

- id: compaction-basic
  name: '@deepseek-ai/dsh-compaction-basic'
  config:
    thresholdRatio: 0.8
    retainRatio: 0.16
    maxTokens: 8192

- id: sessions
  name: '@deepseek-ai/dsh-session-persistence-jsonl'
  config:
    root: !!js process.env.DSH_SESSION_ROOT ?? './.sessions'
    compression: none

- id: session-checkpoints
  name: '@deepseek-ai/dsh-session-checkpoint-policy'
`

var cordisConfigTmpl = template.Must(template.New("cordis").Parse(cordisTemplate))

// RenderCordisConfig generates cordis.yml content from connector settings.
func RenderCordisConfig(cfg *ConnectorConfig) ([]byte, error) {
	var buf bytes.Buffer
	if err := cordisConfigTmpl.Execute(&buf, cfg); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
