package dsh

import (
	"bytes"
	"text/template"
)

// ConnectorConfig holds LLM connector settings for cordis.yml rendering.
type ConnectorConfig struct {
	PiAiRoutes []PiAiRoute // dsh-llm-pi-ai provider routes
	IsWindows  bool
	Vision     bool
}

// PiAiRoute configures one dsh-llm-pi-ai provider route in cordis.yml.
type PiAiRoute struct {
	Name            string            // provider route key (e.g. "yao-primary", "yao-heavy")
	API             string            // wire protocol ("openai-completions" or "anthropic-messages")
	BaseURL         string            // endpoint URL
	APIKeyEnv       string            // env var name for the API key
	Models          []PiAiModelConfig // model catalog for this route
	Reasoning       string            // pi-ai reasoning level; empty = omit
	BudgetTokens    int               // > 0 → output thinkingBudgets
	NoDeveloperRole bool              // true → supportsDeveloperRole: false (safe for all non-OpenAI providers)
	ThinkingFormat  string            // connector-declared thinking wire format (e.g. "deepseek"); empty = let pi-ai detect from URL
}

// PiAiModelConfig declares a model's identity and capabilities for pi-ai.
type PiAiModelConfig struct {
	ID        string   // model identifier
	Input     []string // e.g. ["text"] or ["text", "image"]
	Reasoning bool     // true → render reasoningEfforts block
}

const cordisTemplate = `# Generated by Yao DSH Runner
- id: yaoapp-jsonrpc-stream
  name: '@deepseek-ai/dsh-yaoapp-jsonrpc-stream'
  config:
    maxTokensAsSuccess: true
{{- if .PiAiRoutes }}

- id: llm-pi-ai
  name: '@deepseek-ai/dsh-llm-pi-ai'
  config:
    providers:
{{- range .PiAiRoutes }}
      {{ .Name }}:
        api: {{ .API }}
        baseURL: {{ .BaseURL }}
        apiKeyEnv: {{ .APIKeyEnv }}
{{- if or .NoDeveloperRole .ThinkingFormat }}
        compat:
{{- if .NoDeveloperRole }}
          supportsDeveloperRole: false
{{- end }}
{{- if .ThinkingFormat }}
          thinkingFormat: {{ .ThinkingFormat }}
{{- end }}
{{- end }}
{{- if .Reasoning }}
        reasoning: {{ .Reasoning }}
{{- end }}
{{- if gt .BudgetTokens 0 }}
        thinkingBudgets:
          high: {{ .BudgetTokens }}
{{- end }}
{{- if .Models }}
        models:
{{- range .Models }}
          - id: {{ .ID }}
            input: [{{- range $i, $m := .Input }}{{ if $i }}, {{ end }}{{ $m }}{{- end }}]
{{- if .Reasoning }}
            reasoningEfforts:
              off: none
              low: low
              medium: medium
              high: high
              max: max
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Vision }}

- id: attachment-local
  name: '@deepseek-ai/dsh-attachment-local'
{{- end }}

- id: subprocess
  name: '@deepseek-ai/dsh-subprocess-local'

{{- if .IsWindows }}

- id: pwsh
  name: '@deepseek-ai/dsh-pwsh-local'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()
    timeoutMs: 120000

- id: shell-env
  name: '@deepseek-ai/dsh-shell-env'

- id: tool-pwsh
  name: '@deepseek-ai/dsh-tool-pwsh'

{{- else }}

- id: bash
  name: '@deepseek-ai/dsh-bash-local'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()
    timeoutMs: 120000

- id: shell-env
  name: '@deepseek-ai/dsh-shell-env'

- id: tool-bash
  name: '@deepseek-ai/dsh-tool-bash'
  config:
    enableRunInBackground: false

{{- end }}

- id: session-projection
  name: '@deepseek-ai/dsh-session-projection'

- id: agent-instructions
  name: '@deepseek-ai/dsh-agent-instructions'
  config:
    maxBytes: 16384

- id: timer
  name: '@deepseek-ai/cordis-plugin-timer'

- id: llm
  name: '@deepseek-ai/dsh-llm'

- id: session
  name: '@deepseek-ai/dsh-session'

- id: session-title
  name: '@deepseek-ai/dsh-session-title'
  config:
    fallbackMaxWords: 5
    fallbackMaxBytes: 40
    maxTitleBytes: 80

- id: system-prompt
  name: '@deepseek-ai/dsh-system-prompt'
  config:
    persona: !!js process.env.DSH_SYSTEM_PROMPT ?? 'You are a coding agent.'

- id: tools
  name: '@deepseek-ai/dsh-tools'

- id: agent
  name: '@deepseek-ai/dsh-agent'

- id: llm-retry
  name: '@deepseek-ai/dsh-llm-retry'

- id: jobs
  name: '@deepseek-ai/dsh-jobs-local'

- id: invariants
  name: '@deepseek-ai/dsh-invariants'

- id: session-invariant
  name: '@deepseek-ai/dsh-session/invariant'

- id: agent-invariant
  name: '@deepseek-ai/dsh-agent/invariant'

- id: scope-invariant
  name: '@deepseek-ai/dsh-scope/invariant'

- id: agent-loop-invariant
  name: '@deepseek-ai/dsh-agent-loop/invariant'

- id: agent-loop
  name: '@deepseek-ai/dsh-agent-loop'
  config:
    agents: []

- id: subagent
  name: '@deepseek-ai/dsh-subagent'

- id: subagent-spawn-in-process
  name: '@deepseek-ai/dsh-subagent-spawn-in-process'
  config:
    providerName: spawn

- id: tool-subagent
  name: '@deepseek-ai/dsh-tool-subagent'
  config:
    provider: spawn
    toolName: subagent
    enableRunInBackground: false

- id: tool-todo
  name: '@deepseek-ai/dsh-tool-todo'
  config:
    allowParallelInProgress: true

- id: fs-local
  name: '@deepseek-ai/dsh-fs-local'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()

- id: fs-observation-policy
  name: '@deepseek-ai/dsh-fs-observation-policy'

- id: tool-fs
  name: '@deepseek-ai/dsh-tool-fs'

- id: token-meter
  name: '@deepseek-ai/dsh-token-meter'

- id: compaction-basic
  name: '@deepseek-ai/dsh-compaction-basic'
  config:
    thresholdRatio: 0.8
    retainRatio: 0.16
    maxTokens: 8192

- id: skill-registry
  name: '@deepseek-ai/dsh-skill'

- id: tool-skill
  name: '@deepseek-ai/dsh-tool-skill'

- id: skill-office
  name: '@deepseek-ai/dsh-skill-office'
  config:
    cli: false
    assetRoot: !!js process.env.DSH_OFFICE_ASSET_ROOT

- id: sessions
  name: '@deepseek-ai/dsh-session-persistence-jsonl'
  config:
    root: !!js process.env.DSH_SESSION_ROOT ?? './.sessions'
    compression: none

- id: session-checkpoints
  name: '@deepseek-ai/dsh-session-checkpoint-policy'
`

var cordisConfigTmpl = template.Must(template.New("cordis").Parse(cordisTemplate))

// RenderCordisConfig generates cordis.yml content from connector settings.
func RenderCordisConfig(cfg *ConnectorConfig) ([]byte, error) {
	var buf bytes.Buffer
	if err := cordisConfigTmpl.Execute(&buf, cfg); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
