name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Build Linux Artifacts Run ID"
        required: false
        type: string
  workflow_run:
    workflows: ["Build Linux Artifacts"]
    types:
      - completed

env:
  DOCKER_IMAGE: yaoapp/yao
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: yao-linux
          path: dist/release
          run-id: ${{ github.event.workflow_run.id || inputs.run_id }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Version
        run: |
          VERSION=$(ls dist/release/yao-*-linux-amd64 | sed 's/.*yao-\(.*\)-unstable-linux-amd64/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/base/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}